### ISSUE TITLE
[IPT2g] Error while attempting to run

### ISSUE THREAD

**Issue by syboxez** [devos50/qemu#173]
First, I get a build error:
```
FAILED: libqemu-arm-softmmu.fa.p/hw_arm_ipod_touch_sha1.c.o 
cc -m64 -mcx16 -Ilibqemu-arm-softmmu.fa.p -I. -I.. -Itarget/arm -I../target/arm -Iqapi -Itrace -Iui -Iui/shader -I/usr/include/pixman-1 -I/usr/include/spice-server -I/usr/include/spice-1 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/opus -I/usr/include/cacard -I/usr/include/sysprof-6 -I/usr/include/nss -I/usr/include/nspr -I/usr/include/openssl -fdiagnostics-color=auto -Wall -Winvalid-pch -std=gnu11 -O2 -g -fstack-protector-strong -Wundef -Wwrite-strings -Wmissing-prototypes -Wstrict-prototypes -Wredundant-decls -Wold-style-declaration -Wold-style-definition -Wtype-limits -Wformat-security -Wformat-y2k -Winit-self -Wignored-qualifiers -Wempty-body -Wnested-externs -Wendif-labels -Wexpansion-to-defined -Wimplicit-fallthrough=2 -Wmissing-format-attribute -Wno-missing-include-dirs -Wno-shift-negative-value -Wno-psabi -Wshadow=local -isystem /home/syboxez/gitstuff/qemu-ios/linux-headers -isystem linux-headers -iquote . -iquote /home/syboxez/gitstuff/qemu-ios -iquote /home/syboxez/gitstuff/qemu-ios/include -iquote /home/syboxez/gitstuff/qemu-ios/host/include/x86_64 -iquote /home/syboxez/gitstuff/qemu-ios/host/include/generic -iquote /home/syboxez/gitstuff/qemu-ios/tcg/i386 -Wno-unused-function -pthread -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fno-strict-aliasing -fno-common -fwrapv -march=native -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIE -isystem../linux-headers -isystemlinux-headers -DNEED_CPU_H '-DCONFIG_TARGET="arm-softmmu-config-target.h"' '-DCONFIG_DEVICES="arm-softmmu-config-devices.h"' -MD -MQ libqemu-arm-softmmu.fa.p/hw_arm_ipod_touch_sha1.c.o -MF libqemu-arm-softmmu.fa.p/hw_arm_ipod_touch_sha1.c.o.d -o libqemu-arm-softmmu.fa.p/hw_arm_ipod_touch_sha1.c.o -c ../hw/arm/ipod_touch_sha1.c
../hw/arm/ipod_touch_sha1.c: In function ‘ipod_touch_sha1_read’:
../hw/arm/ipod_touch_sha1.c:55:72: error: passing argument 1 of ‘swapLong’ makes pointer from integer without a cast [-Wint-conversion]
   55 |                 uint64_t data_length = swapLong(((uint64_t *)s->buffer)[s->buffer_ind / 8 - 1]) / 8;
      |                                                 ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
      |                                                                        |
      |                                                                        uint64_t {aka long unsigned int}
../hw/arm/ipod_touch_sha1.c:3:32: note: expected ‘void *’ but argument is of type ‘uint64_t’ {aka ‘long unsigned int’}
    3 | static uint64_t swapLong(void *X) {
      |                          ~~~~~~^
../hw/arm/ipod_touch_sha1.c:58:17: warning: ‘SHA1_Init’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
   58 |                 SHA1_Init(&ctx);
      |                 ^~~~~~~~~
In file included from /home/syboxez/gitstuff/qemu-ios/include/hw/arm/ipod_touch_sha1.h:9,
                 from ../hw/arm/ipod_touch_sha1.c:1:
/usr/include/openssl/sha.h:49:27: note: declared here
   49 | OSSL_DEPRECATEDIN_3_0 int SHA1_Init(SHA_CTX *c);
      |                           ^~~~~~~~~
../hw/arm/ipod_touch_sha1.c:59:17: warning: ‘SHA1_Update’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
   59 |                 SHA1_Update(&ctx, s->buffer, data_length);
      |                 ^~~~~~~~~~~
/usr/include/openssl/sha.h:50:27: note: declared here
   50 | OSSL_DEPRECATEDIN_3_0 int SHA1_Update(SHA_CTX *c, const void *data, size_t len);
      |                           ^~~~~~~~~~~
../hw/arm/ipod_touch_sha1.c:60:17: warning: ‘SHA1_Final’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
   60 |                 SHA1_Final(s->hashout, &ctx);
      |                 ^~~~~~~~~~
/usr/include/openssl/sha.h:51:27: note: declared here
   51 | OSSL_DEPRECATEDIN_3_0 int SHA1_Final(unsigned char *md, SHA_CTX *c);
      |                           ^~~~~~~~~~
ninja: build stopped: subcommand failed.
make[1]: *** [Makefile:162: run-ninja] Error 1
make[1]: Leaving directory '/home/syboxez/gitstuff/qemu-ios/build'
make: *** [GNUmakefile:6: build] Error 2
```

But after bypassing, I am able to build, but not run:

```
$ ./arm-softmmu/qemu-system-arm -M iPod-Touch,bootrom=/home/syboxez/VMs/ipod_touch_2g/bootrom_240_4,nand=/home/syboxez/VMs/ipod_touch_2g/nand/,nor=/home/syboxez/VMs/ipod_touch_2g/nor_n72ap.bin -serial mon:stdio -cpu max -m 2G -d unimp
Unexpected error in object_property_find_err() at ../qom/object.c:1329:
qemu-system-arm: Property 'ipodtouch.sysic.sysbus-irq[7]' not found
Aborted (core dumped)
```

Host: Arch Linux
Host arch: x86_64
Branch: ipod_touch_2g

**Comment by daniilfigasystems** [comment]
I think you should redownload it

**Comment by syboxez** [comment]
> I think you should redownload it

Redownload what, exactly?

**Comment by daniilfigasystems** [comment]
> > I think you should redownload it
> 
> Redownload what, exactly?

Emulator

**Comment by syboxez** [comment]
> > > I think you should redownload it
> > 
> > 
> > Redownload what, exactly?
> 
> Emulator

I compiled it from source from this git repo twice with the same results. I'm on git hash cae1b51a786daef2c46b8b8e19f1b867e60488bf

**Comment by Patrosi73** [comment]
try with the latest commit as it addressed the swapLong function :)

**Comment by devos50** [comment]
Yes, this is fixed by #176

**Comment by syboxez** [comment]
I'm not getting the build error anymore, but I'm still getting the same runtime error.
